Class {
	#name : #GtOpenApiLicense,
	#superclass : #Object,
	#instVars : [
		'name',
		'url'
	],
	#category : #'GToolkit4OpenAPI-New-Model'
}

{ #category : #accessing }
GtOpenApiLicense >> name [

	^ name
]

{ #category : #accessing }
GtOpenApiLicense >> name: anObject [

	name := anObject
]

{ #category : #accessing }
GtOpenApiLicense >> url [

	^ url
]

{ #category : #accessing }
GtOpenApiLicense >> url: anObject [

	url := anObject
]
