Class {
	#name : #GtOpenApiExternalDocumentation,
	#superclass : #Object,
	#instVars : [
		'description',
		'url'
	],
	#category : #'GToolkit4OpenAPI-New-Model'
}

{ #category : #accessing }
GtOpenApiExternalDocumentation >> description [

	^ description
]

{ #category : #accessing }
GtOpenApiExternalDocumentation >> description: anObject [

	description := anObject
]

{ #category : #accessing }
GtOpenApiExternalDocumentation >> url [

	^ url
]

{ #category : #accessing }
GtOpenApiExternalDocumentation >> url: anObject [

	url := anObject
]
