Trait {
	#name : #TGtOpenApiObjectVisitor,
	#category : #'GToolkit4OpenAPI-Parser'
}

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApi: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiCallback: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiComponents: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiContact: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiExternalDocumentation: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiHeader: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiInfo: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiLicense: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiMediaType: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiOperation: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiParameter: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiPathItem: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiPaths: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiReference: aJsonApiObject [
	
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiRequestBody: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiResponse: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiResponses: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiSchema: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiSecurity: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiServer: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiServerVariable: aJsonApiObject [
]

{ #category : #visiting }
TGtOpenApiObjectVisitor >> visitGtOpenApiTag: aJsonApiObject [
]
